// <auto-generated />
using System;
using CDExcellent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDExcellent.Migrations
{
    [DbContext(typeof(CDE_Dbcontext))]
    [Migration("20230703035313_iniDB")]
    partial class iniDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CDExcellent.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tgThamGia")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAccount");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CDExcellent.Models.BaiViet", b =>
                {
                    b.Property<int>("IdBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiViet"), 1L, 1);

                    b.Property<bool>("DangTai")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaiViet");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("CDExcellent.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"), 1L, 1);

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("CDExcellent.Models.CongViec", b =>
                {
                    b.Property<int>("IdCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCV"), 1L, 1);

                    b.Property<int>("IdLichTrinh")
                        .HasColumnType("int");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCV");

                    b.HasIndex("IdLichTrinh");

                    b.ToTable("CongViec");
                });

            modelBuilder.Entity("CDExcellent.Models.KhaoSat", b =>
                {
                    b.Property<int>("IdKhaoSat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhaoSat"), 1L, 1);

                    b.Property<TimeSpan>("GioKS")
                        .HasColumnType("time");

                    b.Property<int>("IdLichTrinh")
                        .HasColumnType("int");

                    b.Property<int>("IdTieuChi")
                        .HasColumnType("int");

                    b.Property<double>("MucDo")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgayKS")
                        .HasColumnType("datetime2");

                    b.HasKey("IdKhaoSat");

                    b.HasIndex("IdLichTrinh");

                    b.HasIndex("IdTieuChi");

                    b.ToTable("KhaoSat");
                });

            modelBuilder.Entity("CDExcellent.Models.KhuVuc", b =>
                {
                    b.Property<int>("IdKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuVuc"), 1L, 1);

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhuVuc");

                    b.ToTable("KhuVuc");
                });

            modelBuilder.Entity("CDExcellent.Models.KhuVuc_NPP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("IdNPP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhuVuc");

                    b.HasIndex("IdNPP");

                    b.ToTable("KhuVuc_NPP");
                });

            modelBuilder.Entity("CDExcellent.Models.KhuVuc_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKhuVuc");

                    b.HasIndex("IdUser");

                    b.ToTable("KhuVuc_User");
                });

            modelBuilder.Entity("CDExcellent.Models.LichTrinh", b =>
                {
                    b.Property<int>("IdLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichTrinh"), 1L, 1);

                    b.Property<TimeSpan>("GioDB")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKQ")
                        .HasColumnType("time");

                    b.Property<int>("IdNPP")
                        .HasColumnType("int");

                    b.Property<string>("KhachMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fNgay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLichTrinh");

                    b.HasIndex("IdNPP");

                    b.ToTable("LichTrinh");
                });

            modelBuilder.Entity("CDExcellent.Models.NhaPhanPhoi", b =>
                {
                    b.Property<int>("IdNPP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNPP"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNPP");

                    b.ToTable("NhaPhanPhoi");
                });

            modelBuilder.Entity("CDExcellent.Models.ThongBao", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"), 1L, 1);

                    b.Property<string>("ChonAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuaDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdUser");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("CDExcellent.Models.TieuChiKS", b =>
                {
                    b.Property<int>("IdTieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTieuChi"), 1L, 1);

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTieuChi");

                    b.ToTable("TieuChiKS");
                });

            modelBuilder.Entity("CDExcellent.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IAccount")
                        .HasColumnType("int");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTG")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("IAccount");

                    b.HasIndex("IdChucVu");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CDExcellent.Models.CongViec", b =>
                {
                    b.HasOne("CDExcellent.Models.LichTrinh", "LichTrinhs")
                        .WithMany()
                        .HasForeignKey("IdLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichTrinhs");
                });

            modelBuilder.Entity("CDExcellent.Models.KhaoSat", b =>
                {
                    b.HasOne("CDExcellent.Models.LichTrinh", "LichTrinnhs")
                        .WithMany()
                        .HasForeignKey("IdLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExcellent.Models.TieuChiKS", "TieuChiKSs")
                        .WithMany()
                        .HasForeignKey("IdTieuChi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichTrinnhs");

                    b.Navigation("TieuChiKSs");
                });

            modelBuilder.Entity("CDExcellent.Models.KhuVuc_NPP", b =>
                {
                    b.HasOne("CDExcellent.Models.KhuVuc", "KhuVucs")
                        .WithMany()
                        .HasForeignKey("IdKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExcellent.Models.NhaPhanPhoi", "NhaPhanPhois")
                        .WithMany()
                        .HasForeignKey("IdNPP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVucs");

                    b.Navigation("NhaPhanPhois");
                });

            modelBuilder.Entity("CDExcellent.Models.KhuVuc_User", b =>
                {
                    b.HasOne("CDExcellent.Models.KhuVuc", "KhuVucs")
                        .WithMany()
                        .HasForeignKey("IdKhuVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExcellent.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVucs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CDExcellent.Models.LichTrinh", b =>
                {
                    b.HasOne("CDExcellent.Models.NhaPhanPhoi", "NhaPhanPhois")
                        .WithMany()
                        .HasForeignKey("IdNPP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaPhanPhois");
                });

            modelBuilder.Entity("CDExcellent.Models.ThongBao", b =>
                {
                    b.HasOne("CDExcellent.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CDExcellent.Models.User", b =>
                {
                    b.HasOne("CDExcellent.Models.Account", "Accounts")
                        .WithMany()
                        .HasForeignKey("IAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CDExcellent.Models.ChucVu", "chucVus")
                        .WithMany()
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("chucVus");
                });
#pragma warning restore 612, 618
        }
    }
}
